-- Calorify PostgreSQL schema for Render.
-- Flask-SQLAlchemy creates the tables automatically at application startup.

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(120) DEFAULT '',
    email VARCHAR(255) DEFAULT '',
    calorie_goal INTEGER DEFAULT 2000,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_firebase_uid ON users(firebase_uid);

CREATE TABLE IF NOT EXISTS food_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL,
    food_name VARCHAR(255) NOT NULL,
    meal VARCHAR(50) DEFAULT 'Snack',
    calories DOUBLE PRECISION DEFAULT 0,
    protein DOUBLE PRECISION DEFAULT 0,
    carbs DOUBLE PRECISION DEFAULT 0,
    fat DOUBLE PRECISION DEFAULT 0,
    fiber DOUBLE PRECISION DEFAULT 0,
    consumed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_food_uid ON food_entries(firebase_uid);
CREATE INDEX IF NOT EXISTS idx_consumed_at ON food_entries(consumed_at);

CREATE TABLE IF NOT EXISTS daily_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL,
    log_date DATE NOT NULL,
    water_ml INTEGER DEFAULT 0,
    exercise_minutes INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_date UNIQUE(firebase_uid, log_date)
);
